### ISSUE TITLE
Estoy obteniendo un error al momento de ejecutar  ./gradlew build

### ISSUE THREAD

**Issue by luisgithub** [GrupoCorasa/cfdi-base#12] opened 2022-01-07 22:01 UTC
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/luisg/development/cfdi-base/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'cfdi-base'.
> Could not get unknown property 'USERNAME' for extension 'env' of type co.uzzu.dotenv.gradle.DotEnvRoot.

**Comment by hortegag91** [comment] 2022-01-07 22:17
Duplicate of #5

**Closed as completed by hortegag91** 2022-01-07 22:17 UTC
